config/routes.rb
Rails.application.routes.draw do

  # Users auth routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations:'users/registrations'
  },
  path: '',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'registration',
    sign_up: 'new'
  }

  authenticated :user do
    get 'cart' => 'cart#show', as: :cart
    put 'cart/add/:id', to: 'cart#add', as: :add_to
    put 'cart/remove/:id', to: 'cart#remove', as: :remove_from
    put 'cart/change_payment', to: 'cart#require_change_payment', as: :require_change_payment
    post 'cart/checkout' => 'cart#create', as: :cart_checkout


    get 'packages' => 'packages#index', as: :packages
    patch 'packages/add/:package_id' => 'packages#add_package', as: :add_package
    patch 'packages/remove/:package_id' => 'packages#remove_package', as: :remove_package


    post 'payment' => 'checkout#create', as: :payment
    get 'payment' => 'checkout#new'

    get 'events' => 'events#index', as: :events
    get 'my_events' => 'profile#events', as: :my_events
    get 'my_home' => 'profile#home', as: :my_home


    root 'profile#home', as: :authenticated_user_root
  end

  unauthenticated :user do
    root 'pages#index',  as: :unauthenticated_user_root

    namespace :challenge do
      get 'inscription/new' => 'team#new_inscription', as: :new_team_inscription
      post 'inscription' => 'team#create_inscription', as: :team_inscription

      get 'inscription/:team_id/equipe' => 'member#new_inscription', as: :new_members_inscription
      post 'inscription/:team_id/' => 'member#create_inscription', as: :members_inscription
    end

  end

  # Admin auth routes
  devise_for :admin, controllers: {
    sessions: 'admin/auth/sessions',
    confirmations: 'admin/auth/confirmations',
    passwords: 'admin/auth/passwords'
  },
  path: 'admin',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
  }, skip: [:registrations]

  namespace :admin do
    authenticated :admin do
      resources :events do
        resources :schedules, except: [:index, :show]
      end
      resources :event_types, except: [:show]
      resources :packages do
        resources :packages_events_types, only: [:create, :destroy]
      end
      resources :users
      resources :comments
      resources :teams, except: [:new, :create, :edit, :update], scope: "teams"
      post 'teams/:id/confirm_payment' => 'teams#confirm_payment', as: :team_confirm_payment
      patch 'users/:user_id/change_payment' => 'users#set_payment', as: :change_user_payment
      patch 'users/:user_id/remove_from_event/:id' => 'users#remove_from_event', as: :remove_user_from_event
      patch 'users/:user_id/remove_from_all_events' => 'users#remove_from_all_events', as: :remove_user_from_all_events
      resources :admins
    end

    root 'users#index'
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :schedules, dependent: :destroy
  has_many :purchases, dependent: :restrict_with_error
  has_many :buyers, through: :purchases, dependent: :restrict_with_error
  belongs_to :event_type

  validates_presence_of :name, :limit, :price, :event_type_id
  validates_numericality_of :price, :limit, greater_than_or_equal_to: 0
  validates_associated :schedules

  @@foo = 0

  def remaining
    self.limit - self.purchases.count
  end


  def self.event_kinds
     EventType.uniq.pluck(:name)
  end


  def self.event_prices
    kinds = Event.event_kinds
    price = Hash.new
    kinds.each do |kind|
      event_id = EventType.find_by(name:kind)
      events = Event.where("price != 0")
      if !events.find_by(event_type_id:event_id).nil?
         price[kind] = events.find_by(event_type_id: event_id).price
      else
        price[kind] = 0
      end
    end
    price
  end

  def self.days
    days = []
    self.all.each do |event|
      event.schedules.each do |schedule|
        day = schedule.start_time.to_date
        days << day unless day.in?(days)
      end
    end
    days.sort!
  end

  def self.appointments
    schedule_day = Hash.new
    days = self.days
    events = self.all
    days.each do |day|
      schedule_day[day] = []
      events.each do |event|
        event.schedules.each do |schedule|
          schedule_day[day] << schedule if schedule.start_time.to_date == day
          schedule_day[day].sort_by! {|obj| obj.start_time}
        end
      end
    end
    schedule_day
  end

  def self.appointment(my_events)
    schedule_day = Hash.new
    days = Event.days
    events = my_events

    days.each do |day|
      schedule_day[day] = []
      events.each do |event|
        event.schedules.each do |schedule|
          schedule_day[day] << schedule if schedule.start_time.to_date == day
          schedule_day[day].sort_by! {|obj| obj.start_time}
        end
      end
    end
    schedule_day
  end
   #retorna os horários em ordem

  def self.timetables(eventsDay)
    timetables = []

    eventsDay.each do |event|
      event.schedules.each do |schedule|
        timetable = schedule.start_time
        timetables << timetable
      end
    end
    timetables
  end

  def self.cart_total_price(current_user)
    total_price = 0
    partial_price = 0
    event_partial_price = 0

    current_user.get_cart_events.each { |event| event_partial_price += event.price }

    if current_user.package
      partial_price = event_partial_price - current_user.package.package_discount(current_user)
      partial = current_user.package.plus(current_user)
      total_price = current_user.package.price + partial
    else
      total_price = event_partial_price
    end
    total_price
  end

  def circleColor
    "inverse"
  end

  def sideAlt
    @@foo +=1
    if @@foo%2==0
      "timeline-item alt"
    else
      "timeline-item "
    end
  end

  def sideArrow
    if @@foo % 2 ==0
      "arrow-alt"
    else
      "arrow"
    end
  end

#final

  def cart_action(current_user)
    if current_user.events.find_by(id:self.id)
      "Remove from"
    else
      "Add to"
    end
  end

end

app/models/event_type.rb
class EventType < ActiveRecord::Base
	belongs_to :package
	has_many :events, dependent: :restrict_with_error
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
    @event_users = @event.buyers
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to [:admin, @event], notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to [:admin, @event], notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    if @event.destroy
      redirect_to admin_events_url, notice: 'Event was successfully destroyed.'
      
    else
      redirect_to admin_events_url, notice: @event.errors.full_messages[0]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:name, :description, :facilitator, :limit, :price, :event_type_id)
    end



    def erase_event_cart(event_id)
      users = User.all 
      users.each do |user|
      $redis.srem "cart#{user.id}", event_id

    end
  end

end

app/controllers/events_controller.rb
class EventsController < ProfileController
  def index
    @events = Event.all
    @eventsDays = Event.days
    @scheduleHash = Event.appointments
    @my_events = @user.events
    @my_events_day = Event.appointment(@my_events)
    @number = 0
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
  def events_kinds_to_array
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_types_to_array
    event_types_array = [
      ['Selecione', nil]
    ]

    EventType.all.each do |event_type|
      event_types_array << [event_type.name, event_type.id]
    end

    event_types_array
  end
end

app/views/admin/events/_form.html.erb
<%= form_for [:admin, @event] do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :facilitator %>
    <%= f.text_field :facilitator, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :limit %>
    <%= f.number_field :limit, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control ' %>
  </div>
  <div class="form-group">
    <%= f.label :kind %>
    <%= f.select :event_type_id, options_for_select(event_types_to_array, selected: @event.event_type_id), {include_blank: false}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :schedules %>
    <input type="" name="" class="form-control" disabled placeholder="Para editar os horários, salve o evento">
  </div>
  <div class="row form-group m-b-0">
    <%= link_to 'Novo tipo de evento', new_admin_event_type_path, class:'btn btn-primary waves-effect waves-light pull-left' %>
    <%= button_tag action_text, type:'submit', class:'btn btn-primary waves-effect waves-light pull-right' %>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card-box">
      <h4 class="header-title m-t-0 m-b-30"><%= titulo_pagina %></h4>
      <%= render 'form' %>
    </div>
    <div class="panel-footer">
      <%= link_to 'Mostrar', [:admin, @event], class: 'btn btn-primary waves-effect w-md waves-light m-b-5' %>
      <%= link_to "New Schedule", new_admin_event_schedule_path(@event), class:'btn btn-primary waves-effect w-md waves-light m-b-5' %>
      <%= link_to 'Todos os Eventos', admin_events_path, class: 'btn btn-primary waves-effect w-md waves-light m-b-5'%>
    </div>
  </div>
</div>

app/views/admin/events/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card-box table-responsive">
      <h4 class="header-title m-t-0 m-b-30"><%= titulo_pagina %></h4>
      <div class="row">
        <div class="col-sm-6">
          <div class="m-b-30">
            <%= link_to(new_admin_event_path, class:'btn btn-primary waves-effect waves-light') do %>
            Criar Programação <i class="fa fa-plus"></i>
            <% end %>
          </div>
        </div>
      </div>
      <div class="responsive">
        <table class="table table-striped" id="datatable">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Descrição</th>
              <th>Facilitador</th>
              <th>Inscritos</th>
              <th>Categoria</th>
              <th>Vagas restantes/Total</th>
              <th data-orderable="false"></th>
            </tr>
          </thead>
          <tbody>
            <% @events.each do |event| %>
            <tr>
              <td><%= event.name %></td>
              <td><%= event.description %></td>
              <td><%= event.facilitator %></td>
              <td><%= event.buyers.count %></td>
              <td><%= event.event_type.try(:name) %></td>
              <td><%= event.remaining %>/<%= event.limit %></td>
              <td>
                <div class="btn-group m-b-10">
                  <%= link_to admin_event_path(event), class: 'btn btn-primary btn-icon waves-effect' do %>
                    <i class="fa fa-eye"></i>
                  <% end %>
                  <%= link_to edit_admin_event_path(event), class: 'btn btn-primary btn-icon waves-effect' do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to admin_event_path(event), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-danger btn-icon waves-effect' do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div><!-- end col -->
</div>

app/views/admin/events/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card-box">
      <h4 class="header-title m-t-0 m-b-30"><%= titulo_pagina %></h4>
      <%= render 'form' %>
    </div>
    <div class="panel-footer">
      <%= link_to 'Todos os Eventos', admin_events_path, class: 'btn btn-primary waves-effect w-md waves-light m-b-5'%>
    </div>
  </div>
</div>

app/views/admin/events/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-color panel-tabs panel-primary">
      <div class="panel-heading">
        <ul class="nav nav-pills pull-right">
          <li class="active">
            <a href="#info" data-toggle="tab" aria-expanded="true">Sobre</a>
          </li>
          <li class="">
            <a href="#users" data-toggle="tab" aria-expanded="false">Inscritos</a>
          </li>
        </ul>
        <h3 class="panel-title"><%= @event.name %></h3>
      </div>
      <div class="panel-body">
        <div class="tab-content">
          <div id="info" class="tab-pane fade in active">
            <div class="row">
              <div class="col-md-12">
                <p>
                  <%= @event.description %>
                </p>
                <p>
                  <strong>Facilitador: </strong><%= @event.facilitator %>
                </p>
                <p>
                  <strong>Valor: </strong><%= @event.price %>
                </p>
                <p>
                  <strong>Tipo: </strong><%= @event.event_type.try(:name) %>
                </p>
                <p>
                  <strong>Total de inscritos: </strong><%= @event.buyers.count %>
                </p>
                <p>
                  <strong>Total de vagas: </strong><%= @event.limit %>
                </p>
                <p>
                  <strong>Total de vagas restantes: </strong><%= @event.remaining %>
                </p>
                <p>
                  <strong>Horários:</strong>
                </p>
                <ul class="list-group">
                  <% @event.schedules.each do |schedule| %>
                    <li class="list-group-item">
                      Início: <%= time_pt(schedule.start_time) %></br>
                      Fim: <%= time_pt(schedule.end_time) %>
                      <%= link_to 'Deletar', admin_event_schedule_path(@event, schedule), method: :delete, class: 'badge badge-danger' %>
                      <%= link_to 'Editar', edit_admin_event_schedule_path(@event, schedule), class: 'badge badge-primary' %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
          <div id="users" class="tab-pane fade">
            <div class="row">
              <div class="col-md-12">
                <% if  @event_users.empty? %>
                  <p>Nenhum usuário inscrito</p>
                <% else %>
                  <div class="responsive">
                    <table class="table table-striped" id="datatable">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Email</th>
                          <th>Course</th>
                          <th>Semester</th>
                          <th>University</th>
                          <th>Nascimento</th>
                          <th data-orderable="false"></th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @event_users.each do |event_user| %>
                        <tr>
                          <td><%= event_user.name %></td>
                          <td><%= event_user.email %></td>
                          <td><%= event_user.course %></td>
                          <td><%= event_user.semester %></td>
                          <td><%= event_user.university %></td>
                          <td><%= event_user.birthday %></td>
                          <td class="actions pull-right">
                            <%= link_to admin_user_path(event_user), class: 'badge badge-primary' do %>
                              <p>Vizualizar</p>
                            <% end %>
                          </td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <%= link_to 'Editar', edit_admin_event_path(@event), class: 'btn btn-primary waves-effect w-md waves-light m-b-5' %>
        <%= link_to "Novo Horário", new_admin_event_schedule_path(@event), class:'btn btn-primary waves-effect w-md waves-light m-b-5' %>
        <%= link_to 'Todos os Eventos', admin_events_path, class: 'btn btn-primary waves-effect w-md waves-light m-b-5'%>
      </div>
    </div>
  </div><!-- end col -->
</div>