config/routes.rb
Rails.application.routes.draw do

  # Users auth routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations:'users/registrations'
  },
  path: '',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'registration',
    sign_up: 'new'
  }

  authenticated :user do
    get 'cart' => 'cart#show', as: :cart
    put 'cart/add/:id', to: 'cart#add', as: :add_to
    put 'cart/remove/:id', to: 'cart#remove', as: :remove_from
    put 'cart/change_payment', to: 'cart#require_change_payment', as: :require_change_payment
    post 'cart/checkout' => 'cart#create', as: :cart_checkout


    get 'packages' => 'packages#index', as: :packages
    patch 'packages/add/:package_id' => 'packages#add_package', as: :add_package
    patch 'packages/remove/:package_id' => 'packages#remove_package', as: :remove_package


    post 'payment' => 'checkout#create', as: :payment
    get 'payment' => 'checkout#new'

    get 'events' => 'events#index', as: :events
    get 'my_events' => 'profile#events', as: :my_events
    get 'my_home' => 'profile#home', as: :my_home


    root 'profile#home', as: :authenticated_user_root
  end

  unauthenticated :user do
    root 'pages#index',  as: :unauthenticated_user_root

    namespace :challenge do
      get 'inscription/new' => 'team#new_inscription', as: :new_team_inscription
      post 'inscription' => 'team#create_inscription', as: :team_inscription

      get 'inscription/:team_id/equipe' => 'member#new_inscription', as: :new_members_inscription
      post 'inscription/:team_id/' => 'member#create_inscription', as: :members_inscription
    end

  end

  # Admin auth routes
  devise_for :admin, controllers: {
    sessions: 'admin/auth/sessions',
    confirmations: 'admin/auth/confirmations',
    passwords: 'admin/auth/passwords'
  },
  path: 'admin',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
  }, skip: [:registrations]

  namespace :admin do
    authenticated :admin do
      resources :events do
        resources :schedules, except: [:index, :show]
      end
      resources :event_types, except: [:show]
      resources :packages do
        resources :packages_events_types, only: [:create, :destroy]
      end
      resources :users
      resources :comments
      resources :teams, except: [:new, :create, :edit, :update], scope: "teams"
      post 'teams/:id/confirm_payment' => 'teams#confirm_payment', as: :team_confirm_payment
      patch 'users/:user_id/change_payment' => 'users#set_payment', as: :change_user_payment
      patch 'users/:user_id/remove_from_event/:id' => 'users#remove_from_event', as: :remove_user_from_event
      patch 'users/:user_id/remove_from_all_events' => 'users#remove_from_all_events', as: :remove_user_from_all_events
      resources :admins
    end

    root 'users#index'
  end

end

app/views/admin/admins/_form.html.erb
<%= form_for [:admin, @admin_admin] do |f| %>
    <% if @admin_admin.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@admin_admin.errors.count, "error") %> prohibited this admin_admin from being saved:</h2>

        <ul>
        <% @admin_admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group text-right m-b-0">
      <%= button_tag "Gravar", type:'submit', class:'btn btn-purple waves-effect waves-light' %>
    </div>
<% end %>

app/views/admin/admins/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card-box">
      <h4 class="header-title m-t-0 m-b-30"><%= titulo_pagina %></h4>
      <%= render 'form' %>
    </div>
  </div>
</div>
<div class="panel-footer">
  <%= link_to 'Exibir', admin_admin_path(@admin_admin), class: 'btn btn-primary waves-effect w-md waves-light m-b-5' %>
  <%= link_to 'Listar', admin_admins_path, class: 'btn btn-primary waves-effect w-md waves-light m-b-5'%>
</div>

app/views/admin/admins/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-12">
    <div class="card-box table-responsive">
      <h4 class="header-title m-t-0 m-b-30"><%= titulo_pagina %></h4>
      <div class="row">
        <div class="col-sm-6">
          <div class="m-b-30">
            <%= link_to(new_admin_admin_path, class:'btn btn-primary waves-effect waves-light') do %>
            New Admin <i class="fa fa-plus"></i>
            <% end %>
          </div>
        </div>
      </div>
      <div class="responsive">
        <table class="table table-striped" id="datatable">
          <thead>
            <tr>
              <th>Email</th>
              <th data-orderable="false"></th>
            </tr>
          </thead>
          <tbody>
            <% @admin_admins.each do |admin_admin| %>
              <% if admin_admin != current_admin %>
                <tr>
                  <td><%= admin_admin.email %></td>
                  <td class="actions pull-right">
                    <div class="btn-group m-b-10">
                      <%= link_to admin_admin_path(admin_admin), class: 'btn btn-primary btn-icon waves-effect' do %>
                        <i class="fa fa-eye"></i>
                      <% end %>
                      <%= link_to edit_admin_admin_path(admin_admin), class: 'btn btn-primary btn-icon waves-effect' do %>
                        <i class="fa fa-edit"></i>
                      <% end %>
                      <%= link_to admin_admin_path(admin_admin), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-danger btn-icon waves-effect' do %>
                        <i class="fa fa-trash"></i>
                      <% end %>
                    </div>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div><!-- end col -->
</div>

app/views/admin/admins/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card-box">
      <h4 class="header-title m-t-0 m-b-30"><%= titulo_pagina %></h4>
      <%= render 'form' %>
    </div>
  </div>
</div>
<%= link_to 'Back', admin_admins_path %>

app/views/admin/admins/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-color panel-tabs panel-primary">
      <div class="panel-heading">
        <ul class="nav nav-pills pull-right">
          <li class="active">
            <a href="#info" data-toggle="tab" aria-expanded="true">Sobre</a>
          </li>
        </ul>
        <h3 class="panel-title">Administrador</h3>
      </div>
      <div class="panel-body">
        <div class="tab-content">
          <div id="info" class="tab-pane fade in active">
            <div class="row">
              <div class="col-md-12">
                <p>
                  <%= @admin_admin.email %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <%= link_to 'Listar', admin_admins_path, class: 'btn btn-primary waves-effect w-md waves-light m-b-5'%>
      </div>
    </div>
  </div><!-- end col -->
</div>