config/routes.rb
Rails.application.routes.draw do

  # Users auth routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations:'users/registrations'
  },
  path: '',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'registration',
    sign_up: 'new'
  }

  authenticated :user do
    get 'cart' => 'cart#show', as: :cart
    put 'cart/add/:id', to: 'cart#add', as: :add_to
    put 'cart/remove/:id', to: 'cart#remove', as: :remove_from
    put 'cart/change_payment', to: 'cart#require_change_payment', as: :require_change_payment
    post 'cart/checkout' => 'cart#create', as: :cart_checkout


    get 'packages' => 'packages#index', as: :packages
    patch 'packages/add/:package_id' => 'packages#add_package', as: :add_package
    patch 'packages/remove/:package_id' => 'packages#remove_package', as: :remove_package


    post 'payment' => 'checkout#create', as: :payment
    get 'payment' => 'checkout#new'

    get 'events' => 'events#index', as: :events
    get 'my_events' => 'profile#events', as: :my_events
    get 'my_home' => 'profile#home', as: :my_home


    root 'profile#home', as: :authenticated_user_root
  end

  unauthenticated :user do
    root 'pages#index',  as: :unauthenticated_user_root

    namespace :challenge do
      get 'inscription/new' => 'team#new_inscription', as: :new_team_inscription
      post 'inscription' => 'team#create_inscription', as: :team_inscription

      get 'inscription/:team_id/equipe' => 'member#new_inscription', as: :new_members_inscription
      post 'inscription/:team_id/' => 'member#create_inscription', as: :members_inscription
    end

  end

  # Admin auth routes
  devise_for :admin, controllers: {
    sessions: 'admin/auth/sessions',
    confirmations: 'admin/auth/confirmations',
    passwords: 'admin/auth/passwords'
  },
  path: 'admin',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
  }, skip: [:registrations]

  namespace :admin do
    authenticated :admin do
      resources :events do
        resources :schedules, except: [:index, :show]
      end
      resources :event_types, except: [:show]
      resources :packages do
        resources :packages_events_types, only: [:create, :destroy]
      end
      resources :users
      resources :comments
      resources :teams, except: [:new, :create, :edit, :update], scope: "teams"
      post 'teams/:id/confirm_payment' => 'teams#confirm_payment', as: :team_confirm_payment
      patch 'users/:user_id/change_payment' => 'users#set_payment', as: :change_user_payment
      patch 'users/:user_id/remove_from_event/:id' => 'users#remove_from_event', as: :remove_user_from_event
      patch 'users/:user_id/remove_from_all_events' => 'users#remove_from_all_events', as: :remove_user_from_all_events
      resources :admins
    end

    root 'users#index'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_one :payment
  has_many :purchases, foreign_key: :buyer_id, dependent: :destroy
  has_many :events, through: :purchases
  has_one :inscription, dependent: :destroy
  has_one :package, through: :inscription
  validates_associated :package

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates_date :birthday
  validates :birthday, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :course, presence: true, length: { maximum: 60 }
  validates :university, presence: true, length: { maximum: 70 }
  validates :semester, presence: true
  validates :size, presence: true, length: { minimum: 1 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 6 }, on: :create

  def cart_count
    self.events.count
  end

  def get_cart_events
   self.events
  end

  def purchase_cart_events!
    get_cart_events.each { |event| purchase(event) }
    $redis.del "cart#{id}"
  end

  def purchase(event)
    events << event unless purchase?(event)
  end

  def purchase?(event)
    events.include?(event)
  end

  def is_there_payment?
    self.payment.nil?
  end

  def is_there_package?
    self.try(:package).nil?
  end

  def events_kind_count
    events = self.events
    count = Hash.new
    kinds = Event.event_kinds
    kinds.each do |kind|
      count[kind] = 0
      events.each do |event|
        count[kind] +=1 if event.event_type.name == kind && event.price != 0
      end
    end
    count
  end

  def package_fit?
    count = self.events_kind_count
    package = self.package
    counter = 0
    package.packages_events_types.each do |package_event_type|
      name = package_event_type.event_type.name
      if count[name] >= package_event_type.limit
       counter +=1
      end
    end

    if counter == package.event_types.count
      true
    else
      false
    end
  end

  private
  def set_package
    flag = false
    if Package.count == 1
      self.package = Package.first
      flag = true
    elsif Package.count > 1
      flag = true
    end
    flag
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/users
  def index
    @admin_users = User.all
  end

  # GET /admin/users/1
  def show
    @payment = @admin_user.payment
    @package = @admin_user.package
  end

  # GET /admin/users/new
  def new
    @admin_user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  def set_payment
    @admin_user = User.find(params[:user_id])

    if @admin_user.payment.update(method: params[:payment_method], status: params[:status])
      Admin::PaymentMailer.status(@admin_user, @admin_user.payment).deliver_now
      redirect_to admin_users_path, notice: 'Pagamento alterado com sucesso!'
    else
      redirect_to :back
    end
  end

  def remove_from_event
    @admin_user = User.find(params[:user_id])
    @event = Event.find(params[:id])
    if @admin_user.events.destroy(@event)
      render :show, notice: 'Usuário removido do evento!'
    end
  end

  def remove_from_all_events
    @admin_user = User.find(params[:user_id])
    if @admin_user.events.destroy_all
      render :show, notice: 'Usuário removido de todos os eventos!'
    end
  end

  # POST /admin/users
  def create
    @admin_user = User.new(admin_user_params)
    generated_password = Devise.friendly_token.first(8)
    @admin_user.password = generated_password
    if @admin_user.save
      @admin_user.confirm
      Admin::RegistrationMailer.welcome(@admin_user, generated_password).deliver_now
      redirect_to [:admin, @admin_user], notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/users/1
  def update
    if @admin_user.update(admin_user_params)
      redirect_to [:admin, @admin_user], notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/users/1
  def destroy
    @admin_user.destroy
    redirect_to admin_users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def admin_user_params
      params.require(:user).permit(:name, :email, :course, :semester, :birthday, :university)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

 private
  def after_confirmation_path_for(resource_name, resource)
    new_user_session_path
  end
  
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  layout 'profile_layout', only: [:edit, :update]

  before_filter :configure_sign_up_params, only: [:create]
  before_filter  :configure_account_update_params, only: [:edit, :update]
  # GET /resource/sign_up
   # def new
   #   super
   # end

  # POST /resource
  # def create
  #  super
  # end

  # GET /resource/edit
  def edit
    @user = current_user
    super
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:name,:email, :course, :semester, :birthday, :university, :size])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
   def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :course, :semester, :birthday, :university, :size])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @admin_user] do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "Erro") %></h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :course %>
    <%= f.text_field :course, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :semester %>
    <%= f.number_field :semester, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :birthday %>
    <%= to_date_field f, @admin_user, :birthday, {class: "date form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :university %>
    <%= f.text_field :university, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :size, "Tamanho da blusa"   %><br />
    <%= f.select :size, options_for_select(sizes_to_array, selected: @admin_user.size), {}, class: 'form-control' %>
  </div>
  <div class="form-group text-right m-b-0">
    <%= button_tag "Save User", type:'submit', class:'btn btn-purple waves-effect waves-light' %>
  </div>
<% end %>

app/views/admin/users/_payment.html.erb
<%= form_tag(admin_change_user_payment_path(@admin_user), method: :patch, class: 'form-horizontal') do %>
  <div class="form-group">
    <label class="col-md-4 control-label">Método de pagamento </label>
    <div class="col-md-8">
      <%= select_tag(:payment_method, options_for_select(@payment.accepted_payment_methods, selected: @payment.method
      ), class:'form-control') %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-md-4 control-label">Status do pagamento </label>
    <div class="col-md-8">
      <%= select_tag(:status, options_for_select(@payment.accepted_payment_status, selected: @payment.status), class:'form-control') %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-10 col-sm-2">
      <button type="submit" class="btn btn-primary">
        Salvar
      </button>
    </div>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card-box">
      <h4 class="header-title m-t-0 m-b-30"><%= titulo_pagina %></h4>
      <%= render 'form' %>
    </div>
  </div>
</div>
<%= link_to 'Show', admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-12">
    <div class="card-box table-responsive">
      <h4 class="header-title m-t-0 m-b-30"><%= titulo_pagina %></h4>
      <div class="row">
        <div class="col-sm-6">
          <div class="m-b-30">
            <%= link_to(new_admin_user_path, class:'btn btn-primary waves-effect waves-light') do %>
            New User <i class="fa fa-plus"></i>
            <% end %>
          </div>
        </div>
      </div>
      <div class="responsive">
        <table class="table table-striped" id="datatable">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Email</th>
              <th>Cursorse</th>
              <th>Semestre</th>
              <th>Aniversário</th>
              <th>Universidade</th>
              <th>Tam. Camisa</th>
              <th>Total da compra</th>
              <th>Data da compra</th>
              <th>Metodo de Pagamento</th>
              <th>Status do Pagamento</th>
              <th data-orderable="false"></th>
            </tr>
          </thead>
          <tbody>
            <% @admin_users.each do |admin_user| %>
            <tr>
              <td><%= admin_user.name %></td>
              <td><%= admin_user.email %></td>
              <td><%= admin_user.course %></td>
              <td><%= admin_user.semester %></td>
              <td><%= date_pt admin_user.birthday %></td>
              <td><%= admin_user.university %></td>
              <td><%= admin_user.size %></td>
              <%if admin_user.payment %>
                <td><%= admin_user.payment.price %></td>
                <td><%= date_pt admin_user.payment.created_at %></td>
              <%else%>
                <td>não possui compra</td>
                <td>não possui compra</td>
              <%end%>
              <td><%= admin_user.payment.try(:method) %></td>
              <td><%= admin_user.payment.try(:status) %></td>
              <td class="actions pull-right">
                <div class="btn-group m-b-10">
                  <%= link_to  admin_user_path(admin_user), class: 'btn btn-primary btn-icon waves-effect' do %>
                  <i class="fa fa-eye"></i>
                  <% end %>
                  <%= link_to edit_admin_user_path(admin_user), class: 'btn btn-primary btn-icon waves-effect' do %>
                  <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to admin_user_path(admin_user), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-danger btn-icon waves-effect' do %>
                  <i class="fa fa-trash"></i>
                  <% end %>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card-box">
      <h4 class="header-title m-t-0 m-b-30"><%= titulo_pagina %></h4>
      <%= render 'form' %>
    </div>
  </div>
</div>
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6">
    <div class="card-box">
      <h4 class="header-title m-t-0 m-b-30">Perfil</h4>
      <div>
        <div class="text-left">
          <p class="text-muted"><strong>Nome :</strong> <span class="m-l-15"><%= @admin_user.name %></span></p>

          <p class="text-muted"><strong>Email :</strong><span class="m-l-15"><%= @admin_user.email %></span></p>

          <p class="text-muted"><strong>Curso :</strong> <span class="m-l-15"><%= @admin_user.course %></span></p>

          <p class="text-muted"><strong>Semestre :</strong> <span class="m-l-15"><%= @admin_user.semester %></span></p>
          <p class="text-muted"><strong>Data de Nascimento :</strong> <span class="m-l-15"><%= @admin_user.birthday %></span></p>
          <p class="text-muted"><strong>Instituição de Ensino :</strong> <span class="m-l-15"><%= @admin_user.university %></span></p>
          <p class="text-muted"><strong>Tamanho da camisa :</strong> <span class="m-l-15"><%= @admin_user.size %></span></p>
        </div>

      </div>

    </div>
  </div>
  <div class="col-md-6">
    <div class="card-box">
      <h4 class="header-title m-t-0 m-b-30">Informações de Pagamento</h4>

      <div class="text-center">
        <% if !@payment.nil? %>
          <div class="text-left">
            <p class="text-muted"><strong>Método atual :</strong>
              <span class="m-l-15"> <%= @payment.method %></span>
            </p>
            <p class="text-muted"><strong>Status atual :</strong>
              <span class="m-l-15"><%= @payment.status %></span>
            </p>
          </div>
          <%= render 'payment'%>
        <% else %>
          <p>Este usuário ainda não escolheu o método de pagamento</p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card-box">
      <h4 class="header-title m-t-0 m-b-30">Informações do Pacote</h4>

        <% if !@package.nil? %>
          <ul class="list-group m-b-0 user-list">
            <li class="list-group-item user-list-item">
              <div class="avatar text-center">
                <i class="zmdi zmdi-circle text-primary"></i>
              </div>
              <div class="user-desc">
                <span class="name"> Pacote <%= @package.title %></span>
                <span class="desc"> R$ <%= @package.price %></span>
              </div>
            </li>
          </ul>
        <% else %>
          <div class="text-center">
            <p>Este usuário ainda não escolheu seu pacote</p>
          </div>
        <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card-box">
      <h4 class="header-title m-t-0 m-b-30">Eventos</h4>
      <% if @admin_user.events.empty? %>
        <div class="text-center">
          <p>Usuario não está inscrito em nenhum evento</p>
        </div>
      <% else %>
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th>Evento</th>
                <th>Horário</th>
                <th>Opções</th>
                <th><%= link_to 'Remover de todos', admin_remove_user_from_all_events_path(@admin_user), method: :patch, class:'label label-danger' %></th>
              </tr>
            </thead>
            <tbody>
              <% @admin_user.events.each do |event| %>
                <tr>
                  <td><%= event.name %></td>
                  <td><%= event.description %></td>
                  <td><%= link_to 'Remover', admin_remove_user_from_event_path(@admin_user, event), method: :patch, class:'label label-danger' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>